name: Codecov Coverage
on:
  push:
    branches: [develop, beta, alpha]
    # branches: [main, beta, alpha]

jobs:
  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfilee

      - name: Generate Report for each project
        run: yarn nx run-many --all --target=test --codeCoverage --passWithNoTests --runInBand --no-cache

      - name: Generate Report for whole monorepo
        run: yarn jest --coverage

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Initialize MySQL Server
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'test'
          mysql user: 'tester'
          mysql password: 'test'

      - name: Generate Report for api e2e tests
        run: yarn nx e2e api --code-coverage

      - name: Codecov Upload
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: './coverage/'
          dry_run: true
