name: Test-Build

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
  pull_request:
  push:
    branches: [main, beta, develop]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: yarn install
      - run: yarn nx affected --target=test --parallel

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: yarn install
      - run: yarn nx affected --target=build --prod --parallel
